### ISSUE TITLE
"Edit this page button" not working 

### ISSUE THREAD

**Issue by daaronr** [WillemSleegers/how-to-science#1]
https://github.com/willemsleegers/how-to-science/edit/main/content/statistics/factor-analysis/EFA/EFA-best-practices.qmd

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/8229168/175829209-c8153a32-391d-4b4d-a2c8-7c127888ee8e.png">

goes to dead link

**Comment by WillemSleegers** [comment]
You don't provide a lot of context. I assume this happens when you click on 'Edit this page'?

**Comment by WillemSleegers** [comment]
Should work now

**Comment by daaronr** [comment]
Yes, it works now, thanks.
